---
settings:
  crawler_storage: 'mongodb'
database:
  mongodb:
    uri: 'mongodb://${MONGODB_HOST}:${MONGODB_PORT}'
    host: '${MONGODB_HOST}'
    port: '${MONGODB_PORT}'
    username: '${MONGODB_USER}'
    password: '${MONGODB_PWD}'
    dflt_conn_db: '${MONGODB_DEFAULT_CONN_DB}'
    dflt_conn_collection: '${MONGODB_DEFAULT_CONN_COLLECTION}'
